// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ScadaCore.Data;

#nullable disable

namespace ScadaCore.ValuesAndAlarmsDbMigrations
{
    [DbContext(typeof(ValueAndAlarmContext))]
    partial class ValueAndAlarmContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ScadaCore.Models.AlarmLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AlarmId")
                        .HasColumnType("int");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("Id");

                    b.ToTable("AlarmLogs");
                });

            modelBuilder.Entity("ScadaCore.Models.TagLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("TagName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("TagLogs");

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("ScadaCore.Models.AnalogTagLog", b =>
                {
                    b.HasBaseType("ScadaCore.Models.TagLog");

                    b.Property<decimal>("EmittedValue")
                        .HasColumnType("decimal(18,2)");

                    b.ToTable("AnalogTagLogs");
                });

            modelBuilder.Entity("ScadaCore.Models.DigitalTagLog", b =>
                {
                    b.HasBaseType("ScadaCore.Models.TagLog");

                    b.Property<bool>("EmittedValue")
                        .HasColumnType("bit");

                    b.ToTable("DigitalTagLogs");
                });

            modelBuilder.Entity("ScadaCore.Models.AnalogTagLog", b =>
                {
                    b.HasOne("ScadaCore.Models.TagLog", null)
                        .WithOne()
                        .HasForeignKey("ScadaCore.Models.AnalogTagLog", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ScadaCore.Models.DigitalTagLog", b =>
                {
                    b.HasOne("ScadaCore.Models.TagLog", null)
                        .WithOne()
                        .HasForeignKey("ScadaCore.Models.DigitalTagLog", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
